### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by davidraker**
Updates to documentation.

### CODE REVIEW

**Comment by craig8** [comment]
Same issue as in the other repos on the docs

image

**Comment by craig8** [comment]
Please add the python3.10 and python3.11 badges as well see https://github.com/eclipse-volttron/volttron-core/edit/main/README.md line 4-6

**Comment by craig8** [comment]
The indention

**Comment by schandrika** [comment]
Local build of docs fails. 
```
(volttron-lib-bacnet-driver-py3.10) volttron@evolttron1:~/git/volttron-lib-bacnet-driver/docs$ make html
Running Sphinx v4.5.0
[autosummary] generating autosummary for: bacnet-auto-configuration.rst, index.rst
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://www.sphinx-doc.org/en/master/objects.inv...

 

Extension error:
Handler <function generate_agent_docs at 0x7f5f3a0ceef0> for event 'builder-inited' threw an exception (exception: [Errno 2] No such file or directory: '/home/volttron/git/volttron-lib-bacnet-driver/docs/source/agent-docs')
make: *** [Makefile:20: html] Error 2
```

If I remove the custom method from conf.py(everything after line 60) local build is successful and docs look right

**Pull request merged**
